"""Publishable figures (Stage 4/6): reliability diagram, accuracy-by-difficulty,
cost-vs-accuracy scatter, failure-type stacked bar. Save PNGs to results/figures/.
"""

def reliability_diagram(confidences, correct, path): ...
def accuracy_by_difficulty(records, path): ...
def cost_vs_accuracy(summary, path): ...
